// app/layout.tsx (Server Component)
import { SessionProvider } from "next-auth/react";
import { Metadata } from "next";
import "../styles/globals.css"; // Import global styles

// This layout is still a server component, so no "use client" directive
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
